// Single source of truth for every icon name the builder can reference: the
// icon control's content picker (FieldControls), the widget-type icons in the
// block library (LeftPanel, via lib/builder/registry.ts), and the published
// renderer (BuilderRenderer). Explicit named imports here — never
// `import * as Lucide` — so the bundler can tree-shake every icon this app
// doesn't use. The whole `lucide-react` package is ~1000 components; a
// namespace import pulls in all of them regardless of which few are ever
// referenced by name at runtime.
import {
  ArrowRight,
  ArrowUpRight,
  Box,
  Briefcase,
  Check,
  ChevronsUpDown,
  Clock3,
  Coffee,
  Facebook,
  FileCheck2,
  Factory,
  Flag,
  GalleryHorizontal,
  Gift,
  Globe,
  Grid2x2,
  Hash,
  Heading,
  Heart,
  Image,
  Instagram,
  LayoutGrid,
  LayoutPanelTop,
  Linkedin,
  List,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Minus,
  MousePointerClick,
  MoveVertical,
  Package,
  Phone,
  Play,
  Plus,
  Rows3,
  Search,
  Send,
  Share2,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Star,
  Tag,
  Truck,
  Twitter,
  Type,
  Wrench,
  Youtube,
  type LucideIcon,
} from "lucide-react";

/** Icons offered in the builder's content icon picker (FieldControls). */
export const contentIconRegistry: Record<string, LucideIcon> = {
  ArrowUpRight,
  ArrowRight,
  Check,
  Plus,
  Star,
  Sparkles,
  Heart,
  Mail,
  Phone,
  MapPin,
  Clock3,
  Send,
  MessageCircle,
  ShoppingCart,
  ShoppingBag,
  Package,
  Truck,
  Factory,
  FileCheck2,
  Shirt,
  Coffee,
  Flag,
  Gift,
  Briefcase,
  Wrench,
  Image,
  Play,
  Instagram,
  Linkedin,
  Facebook,
  Twitter,
  Youtube,
  Globe,
  Menu,
  Search,
};

/** Icons used for widget/block types in the builder's left panel. */
const widgetIconRegistry: Record<string, LucideIcon> = {
  Rows3,
  Box,
  LayoutGrid,
  Heading,
  Type,
  Tag,
  MousePointerClick,
  ArrowUpRight,
  List,
  LayoutPanelTop,
  Hash,
  ChevronsUpDown,
  MoveVertical,
  Minus,
  Image,
  Sparkles,
  Star,
  Play,
  Menu,
  Share2,
  Package,
  Grid2x2,
  Wrench,
  Briefcase,
  GalleryHorizontal,
  Send,
};

/** Every icon the builder can resolve by name, content and widget sets combined. */
export const iconRegistry: Record<string, LucideIcon> = {
  ...contentIconRegistry,
  ...widgetIconRegistry,
};

/** Names offered in the builder's content icon picker, in display order. */
export const iconNames = Object.keys(contentIconRegistry);
