/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBuilderRouteImport } from './routes/_authenticated/admin.builder'
import { Route as AuthenticatedAdminCatalogRouteImport } from './routes/_authenticated/admin.catalog'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminSectionsRouteImport } from './routes/_authenticated/admin.sections'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminSocialsRouteImport } from './routes/_authenticated/admin.socials'
import { Route as AuthenticatedAdminThemeRouteImport } from './routes/_authenticated/admin.theme'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminWhatsappRouteImport } from './routes/_authenticated/admin.whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBuilderRoute =
  AuthenticatedAdminBuilderRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogRoute =
  AuthenticatedAdminCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSectionsRoute =
  AuthenticatedAdminSectionsRouteImport.update({
    id: '/sections',
    path: '/sections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSocialsRoute =
  AuthenticatedAdminSocialsRouteImport.update({
    id: '/socials',
    path: '/socials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminThemeRoute = AuthenticatedAdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWhatsappRoute =
  AuthenticatedAdminWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/work/$slug': typeof WorkSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/builder': typeof AuthenticatedAdminBuilderRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/sections': typeof AuthenticatedAdminSectionsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/socials': typeof AuthenticatedAdminSocialsRoute
  '/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/work/$slug': typeof WorkSlugRoute
  '/shop': typeof ShopIndexRoute
  '/admin/builder': typeof AuthenticatedAdminBuilderRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/sections': typeof AuthenticatedAdminSectionsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/socials': typeof AuthenticatedAdminSocialsRoute
  '/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/work/$slug': typeof WorkSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/_authenticated/admin/builder': typeof AuthenticatedAdminBuilderRoute
  '/_authenticated/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/sections': typeof AuthenticatedAdminSectionsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/socials': typeof AuthenticatedAdminSocialsRoute
  '/_authenticated/admin/theme': typeof AuthenticatedAdminThemeRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/home'
    | '/login'
    | '/privacy-policy'
    | '/solutions'
    | '/terms'
    | '/admin'
    | '/category/$slug'
    | '/product/$id'
    | '/work/$slug'
    | '/shop/'
    | '/admin/builder'
    | '/admin/catalog'
    | '/admin/projects'
    | '/admin/sections'
    | '/admin/services'
    | '/admin/socials'
    | '/admin/theme'
    | '/admin/users'
    | '/admin/whatsapp'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/home'
    | '/login'
    | '/privacy-policy'
    | '/solutions'
    | '/terms'
    | '/category/$slug'
    | '/product/$id'
    | '/work/$slug'
    | '/shop'
    | '/admin/builder'
    | '/admin/catalog'
    | '/admin/projects'
    | '/admin/sections'
    | '/admin/services'
    | '/admin/socials'
    | '/admin/theme'
    | '/admin/users'
    | '/admin/whatsapp'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/home'
    | '/login'
    | '/privacy-policy'
    | '/solutions'
    | '/terms'
    | '/_authenticated/admin'
    | '/category/$slug'
    | '/product/$id'
    | '/work/$slug'
    | '/shop/'
    | '/_authenticated/admin/builder'
    | '/_authenticated/admin/catalog'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/sections'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/socials'
    | '/_authenticated/admin/theme'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/whatsapp'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SolutionsRoute: typeof SolutionsRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductIdRoute: typeof ProductIdRoute
  WorkSlugRoute: typeof WorkSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/builder': {
      id: '/_authenticated/admin/builder'
      path: '/builder'
      fullPath: '/admin/builder'
      preLoaderRoute: typeof AuthenticatedAdminBuilderRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalog': {
      id: '/_authenticated/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sections': {
      id: '/_authenticated/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AuthenticatedAdminSectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/socials': {
      id: '/_authenticated/admin/socials'
      path: '/socials'
      fullPath: '/admin/socials'
      preLoaderRoute: typeof AuthenticatedAdminSocialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/theme': {
      id: '/_authenticated/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AuthenticatedAdminThemeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/whatsapp': {
      id: '/_authenticated/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AuthenticatedAdminWhatsappRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBuilderRoute: typeof AuthenticatedAdminBuilderRoute
  AuthenticatedAdminCatalogRoute: typeof AuthenticatedAdminCatalogRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminSectionsRoute: typeof AuthenticatedAdminSectionsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSocialsRoute: typeof AuthenticatedAdminSocialsRoute
  AuthenticatedAdminThemeRoute: typeof AuthenticatedAdminThemeRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWhatsappRoute: typeof AuthenticatedAdminWhatsappRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBuilderRoute: AuthenticatedAdminBuilderRoute,
  AuthenticatedAdminCatalogRoute: AuthenticatedAdminCatalogRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminSectionsRoute: AuthenticatedAdminSectionsRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSocialsRoute: AuthenticatedAdminSocialsRoute,
  AuthenticatedAdminThemeRoute: AuthenticatedAdminThemeRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWhatsappRoute: AuthenticatedAdminWhatsappRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SolutionsRoute: SolutionsRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductIdRoute: ProductIdRoute,
  WorkSlugRoute: WorkSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
