-- Expand the visual editor to every public route and keep published content public-only.
ALTER TABLE public.page_content DROP CONSTRAINT IF EXISTS page_content_page_id_check;
ALTER TABLE public.page_content ADD CONSTRAINT page_content_page_id_check
  CHECK (page_id IN ('home', 'shop', 'solutions', 'about', 'contact', 'category', 'product', 'work', 'services', 'studio'));
ALTER TABLE public.page_published_content DROP CONSTRAINT IF EXISTS page_published_content_page_id_check;
ALTER TABLE public.page_published_content ADD CONSTRAINT page_published_content_page_id_check
  CHECK (page_id IN ('home', 'shop', 'solutions', 'about', 'contact', 'category', 'product', 'work', 'services', 'studio'));

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'page_published_content'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.page_published_content;
  END IF;
END $$;

INSERT INTO public.page_content (page_id, draft, published, draft_revision, published_revision)
VALUES
  ('shop', '{"version":1,"pageId":"shop","title":"Shop","description":"Browse branded merchandise from Triad Studio.","blocks":[{"id":"shop_intro","kind":"rich_text","label":"Shop introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Shop the catalog","heading":"Branded goods, made to move.","body":"Browse live availability, choose what fits your brief, and add items to your cart."},"items":[],"design":{}},{"id":"shop_products","kind":"featured","label":"Product catalog","visible":true,"mobileVisible":true,"content":{"heading":"Browse the catalog"},"items":[],"design":{}}],"seo":{"title":"Shop — Triad Studio","description":"Branded merchandise by Triad Studio.","canonical":"/shop"}}'::jsonb, '{"version":1,"pageId":"shop","title":"Shop","description":"Browse branded merchandise from Triad Studio.","blocks":[{"id":"shop_intro","kind":"rich_text","label":"Shop introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Shop the catalog","heading":"Branded goods, made to move.","body":"Browse live availability, choose what fits your brief, and add items to your cart."},"items":[],"design":{}},{"id":"shop_products","kind":"featured","label":"Product catalog","visible":true,"mobileVisible":true,"content":{"heading":"Browse the catalog"},"items":[],"design":{}}],"seo":{"title":"Shop — Triad Studio","description":"Branded merchandise by Triad Studio.","canonical":"/shop"}}'::jsonb, 1, 1),
  ('solutions', '{"version":1,"pageId":"solutions","title":"Solutions","description":"Branding, design, print and merchandise services.","blocks":[{"id":"solutions_intro","kind":"rich_text","label":"Solutions introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Solutions","heading":"Make the brand impossible to miss.","body":"Strategy, design and production in one connected team."},"items":[],"design":{}},{"id":"solutions_services","kind":"services","label":"Services collection","visible":true,"mobileVisible":true,"content":{},"items":[],"design":{}},{"id":"solutions_cta","kind":"contact_form","label":"Project CTA","visible":true,"mobileVisible":true,"content":{"heading":"Have a brief? Let’s make it work."},"items":[],"design":{}}],"seo":{"title":"Solutions — Triad Studio","description":"Branding, design, print and merchandise services.","canonical":"/solutions"}}'::jsonb, '{"version":1,"pageId":"solutions","title":"Solutions","description":"Branding, design, print and merchandise services.","blocks":[{"id":"solutions_intro","kind":"rich_text","label":"Solutions introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Solutions","heading":"Make the brand impossible to miss.","body":"Strategy, design and production in one connected team."},"items":[],"design":{}},{"id":"solutions_services","kind":"services","label":"Services collection","visible":true,"mobileVisible":true,"content":{},"items":[],"design":{}},{"id":"solutions_cta","kind":"contact_form","label":"Project CTA","visible":true,"mobileVisible":true,"content":{"heading":"Have a brief? Let’s make it work."},"items":[],"design":{}}],"seo":{"title":"Solutions — Triad Studio","description":"Branding, design, print and merchandise services.","canonical":"/solutions"}}'::jsonb, 1, 1),
  ('about', '{"version":1,"pageId":"about","title":"About Triad Studio","description":"An independent Nairobi creative studio.","blocks":[{"id":"about_intro","kind":"rich_text","label":"About introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Studio","heading":"Small enough to care. Serious enough to deliver.","body":"Triad is an independent Nairobi studio for brands that need more than a logo and less than a revolving door of suppliers."},"items":[],"design":{}},{"id":"about_projects","kind":"projects","label":"Selected work","visible":true,"mobileVisible":true,"content":{"heading":"Selected work"},"items":[],"design":{}},{"id":"about_cta","kind":"contact_form","label":"About CTA","visible":true,"mobileVisible":true,"content":{"heading":"Bring the brief. We will bring the point of view."},"items":[],"design":{}}],"seo":{"title":"About — Triad Studio","description":"Meet the independent Triad Studio team.","canonical":"/about"}}'::jsonb, '{"version":1,"pageId":"about","title":"About Triad Studio","description":"An independent Nairobi creative studio.","blocks":[{"id":"about_intro","kind":"rich_text","label":"About introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Studio","heading":"Small enough to care. Serious enough to deliver.","body":"Triad is an independent Nairobi studio for brands that need more than a logo and less than a revolving door of suppliers."},"items":[],"design":{}},{"id":"about_projects","kind":"projects","label":"Selected work","visible":true,"mobileVisible":true,"content":{"heading":"Selected work"},"items":[],"design":{}},{"id":"about_cta","kind":"contact_form","label":"About CTA","visible":true,"mobileVisible":true,"content":{"heading":"Bring the brief. We will bring the point of view."},"items":[],"design":{}}],"seo":{"title":"About — Triad Studio","description":"Meet the independent Triad Studio team.","canonical":"/about"}}'::jsonb, 1, 1),
  ('contact', '{"version":1,"pageId":"contact","title":"Contact Triad Studio","description":"Start a project with Triad Studio.","blocks":[{"id":"contact_intro","kind":"rich_text","label":"Contact introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Contact","heading":"Start with the thing that matters.","body":"A new identity, a launch that needs to land, or a production problem that needs an owner."},"items":[],"design":{}},{"id":"contact_form","kind":"contact_form","label":"Contact form","visible":true,"mobileVisible":true,"content":{"heading":"Tell us what you are building."},"items":[],"design":{}}],"seo":{"title":"Contact — Triad Studio","description":"Start a brief with Triad Studio.","canonical":"/contact"}}'::jsonb, '{"version":1,"pageId":"contact","title":"Contact Triad Studio","description":"Start a project with Triad Studio.","blocks":[{"id":"contact_intro","kind":"rich_text","label":"Contact introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Contact","heading":"Start with the thing that matters.","body":"A new identity, a launch that needs to land, or a production problem that needs an owner."},"items":[],"design":{}},{"id":"contact_form","kind":"contact_form","label":"Contact form","visible":true,"mobileVisible":true,"content":{"heading":"Tell us what you are building."},"items":[],"design":{}}],"seo":{"title":"Contact — Triad Studio","description":"Start a brief with Triad Studio.","canonical":"/contact"}}'::jsonb, 1, 1),
  ('category', '{"version":1,"pageId":"category","title":"Category","description":"Browse products by category.","blocks":[{"id":"category_intro","kind":"rich_text","label":"Category introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Category","heading":"Browse the collection.","body":""},"items":[],"design":{}},{"id":"category_products","kind":"featured","label":"Category products","visible":true,"mobileVisible":true,"content":{},"items":[],"design":{}}],"seo":{"title":"Category — Triad Studio","description":"Browse products by category.","canonical":"/category"}}'::jsonb, '{"version":1,"pageId":"category","title":"Category","description":"Browse products by category.","blocks":[{"id":"category_intro","kind":"rich_text","label":"Category introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Category","heading":"Browse the collection.","body":""},"items":[],"design":{}},{"id":"category_products","kind":"featured","label":"Category products","visible":true,"mobileVisible":true,"content":{},"items":[],"design":{}}],"seo":{"title":"Category — Triad Studio","description":"Browse products by category.","canonical":"/category"}}'::jsonb, 1, 1),
  ('product', '{"version":1,"pageId":"product","title":"Product","description":"Product details.","blocks":[{"id":"product_detail","kind":"rich_text","label":"Product detail","visible":true,"mobileVisible":true,"content":{},"items":[],"design":{}},{"id":"product_cta","kind":"contact_form","label":"Product enquiry","visible":true,"mobileVisible":true,"content":{"heading":"Need a custom quote?"},"items":[],"design":{}}],"seo":{"title":"Product — Triad Studio","description":"Product details from Triad Studio.","canonical":"/product"}}'::jsonb, '{"version":1,"pageId":"product","title":"Product","description":"Product details.","blocks":[{"id":"product_detail","kind":"rich_text","label":"Product detail","visible":true,"mobileVisible":true,"content":{},"items":[],"design":{}},{"id":"product_cta","kind":"contact_form","label":"Product enquiry","visible":true,"mobileVisible":true,"content":{"heading":"Need a custom quote?"},"items":[],"design":{}}],"seo":{"title":"Product — Triad Studio","description":"Product details from Triad Studio.","canonical":"/product"}}'::jsonb, 1, 1),
  ('work', '{"version":1,"pageId":"work","title":"Selected work","description":"Selected projects by Triad Studio.","blocks":[{"id":"work_intro","kind":"rich_text","label":"Work introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Selected work","heading":"Work that earns attention.","body":""},"items":[],"design":{}},{"id":"work_projects","kind":"projects","label":"Projects collection","visible":true,"mobileVisible":true,"content":{},"items":[],"design":{}}],"seo":{"title":"Work — Triad Studio","description":"Selected Triad Studio projects.","canonical":"/work"}}'::jsonb, '{"version":1,"pageId":"work","title":"Selected work","description":"Selected projects by Triad Studio.","blocks":[{"id":"work_intro","kind":"rich_text","label":"Work introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Selected work","heading":"Work that earns attention.","body":""},"items":[],"design":{}},{"id":"work_projects","kind":"projects","label":"Projects collection","visible":true,"mobileVisible":true,"content":{},"items":[],"design":{}}],"seo":{"title":"Work — Triad Studio","description":"Selected Triad Studio projects.","canonical":"/work"}}'::jsonb, 1, 1)
ON CONFLICT (page_id) DO NOTHING;

INSERT INTO public.page_published_content (page_id, document, revision)
SELECT page_id, published, published_revision FROM public.page_content
WHERE page_id IN ('shop', 'solutions', 'about', 'contact', 'category', 'product', 'work')
ON CONFLICT (page_id) DO NOTHING;
