-- Replace the initial policy summaries with complete, editable policy documents.
WITH policy_documents(page_id, document) AS (
  VALUES
    (
      'privacy',
      $$
      {
        "version": 2,
        "pageId": "privacy",
        "title": "Privacy Policy",
        "description": "How Triad Studio collects, uses and protects information when you use this website or contact us.",
        "blocks": [
          {"id":"privacy_intro","kind":"rich_text","label":"Privacy Policy introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Triad Studio | Effective 9 September 2026","heading":"Your information, handled with care.","body":"This Privacy Policy explains how Triad Studio collects, uses, stores and protects personal information when you browse our website, contact us, request a quote, purchase a product or work with us. It applies to information collected online and through our direct enquiry channels."},"items":[],"design":{}},
          {"id":"privacy_controller","kind":"rich_text","label":"Who we are and how to contact us","visible":true,"mobileVisible":true,"content":{"heading":"Who we are","body":"Triad Studio is a branding, print, digital design and branded merchandise studio based in Nairobi, Kenya. We are responsible for deciding how information is used for the purposes described here. For privacy questions, access requests or complaints, email 3.triadstudio@gmail.com or contact us through the details on our Contact page."},"items":[],"design":{}},
          {"id":"privacy_collect","kind":"rich_text","label":"Information we collect","visible":true,"mobileVisible":true,"content":{"heading":"Information we collect","body":"We may collect your name, email address, phone number, company or organisation, delivery or billing details, project brief, budget, preferences, correspondence, files and other information you choose to provide. When you browse the site, we may also receive technical information such as your IP address, browser type, device details, pages viewed, referring page and approximate usage times."},"items":[],"design":{}},
          {"id":"privacy_sources","kind":"rich_text","label":"How we receive information","visible":true,"mobileVisible":true,"content":{"heading":"How information reaches us","body":"We receive information directly from you when you submit a form, email us, start a WhatsApp conversation, place an order, request support or otherwise communicate with us. We may also receive limited technical information from your browser, hosting provider, analytics tools or other service providers that help us operate the website. Please avoid sending passwords, payment card numbers or other sensitive information through a general enquiry form."},"items":[],"design":{}},
          {"id":"privacy_use","kind":"rich_text","label":"How we use information","visible":true,"mobileVisible":true,"content":{"heading":"How we use information","body":"We use information to respond to enquiries, prepare estimates and proposals, process and fulfil orders, coordinate production and delivery, provide support, manage our client relationship, send service-related updates, improve the website and protect our business from misuse or fraud. We may use aggregated or de-identified information to understand broad trends without trying to identify you."},"items":[],"design":{}},
          {"id":"privacy_basis","kind":"rich_text","label":"Why we are allowed to use information","visible":true,"mobileVisible":true,"content":{"heading":"Our reasons for using information","body":"Depending on the context, we use personal information because it is needed to respond to your request or perform an agreement, because we have a legitimate business purpose such as improving and securing our services, because you have given consent, or because the law requires us to do so. Where we rely on consent, you can withdraw it by contacting us; this does not affect processing that took place before withdrawal."},"items":[],"design":{}},
          {"id":"privacy_share","kind":"rich_text","label":"When we share information","visible":true,"mobileVisible":true,"content":{"heading":"When information is shared","body":"We do not sell personal information. We may share the minimum information needed with trusted suppliers, printers, couriers, payment providers, hosting and technology providers, professional advisers or project partners when they help us deliver a service. We may also disclose information where required by law, to protect rights and safety, or as part of a business transfer. Service providers are expected to protect information and use it only for the agreed purpose."},"items":[],"design":{}},
          {"id":"privacy_retention","kind":"rich_text","label":"Retention and security","visible":true,"mobileVisible":true,"content":{"heading":"Retention and security","body":"We keep information only for as long as it is reasonably necessary for the purpose collected, including to complete a project, maintain business and tax records, resolve disputes, enforce agreements and meet legal obligations. We use reasonable administrative, technical and organisational measures to protect information, but no website, email service or electronic transmission can be guaranteed completely secure. Please tell us promptly if you believe information has been sent to us in error or accessed without permission."},"items":[],"design":{}},
          {"id":"privacy_rights","kind":"rich_text","label":"Your privacy choices and rights","visible":true,"mobileVisible":true,"content":{"heading":"Your choices and rights","body":"Subject to applicable law, you may ask us to access the personal information we hold about you, correct inaccurate information, delete information that no longer needs to be retained, restrict or object to certain processing, receive a usable copy of information you provided, or withdraw consent. We may need to verify your identity before responding. Send requests to 3.triadstudio@gmail.com and we will respond within the period required by applicable law."},"items":[],"design":{}},
          {"id":"privacy_transfers","kind":"rich_text","label":"International transfers and children","visible":true,"mobileVisible":true,"content":{"heading":"Transfers and younger visitors","body":"Some providers that support our website or communications may process information outside Kenya. Where this happens, we take reasonable steps to use appropriate safeguards and require providers to protect the information. Our services are not directed at children, and we do not knowingly collect personal information from children through this website. If you believe a child has provided information, please contact us so we can review it."},"items":[],"design":{}},
          {"id":"privacy_changes","kind":"rich_text","label":"Changes and contact","visible":true,"mobileVisible":true,"content":{"heading":"Updates to this policy","body":"We may update this policy when our services, technology or legal obligations change. The updated version will be posted on this page with a new effective date. If a change is material, we may provide a more prominent notice where appropriate. Questions, requests and complaints can be sent to 3.triadstudio@gmail.com."},"items":[],"design":{}}
        ],
        "seo": {"title":"Privacy Policy - Triad Studio","description":"Triad Studio privacy policy.","canonical":"/privacy-policy"}
      }
      $$::jsonb
    ),
    (
      'terms',
      $$
      {
        "version": 2,
        "pageId": "terms",
        "title": "Terms of Use",
        "description": "The terms that apply when you browse this website, request a quote or engage Triad Studio.",
        "blocks": [
          {"id":"terms_intro","kind":"rich_text","label":"Terms of Use introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Triad Studio | Effective 9 September 2026","heading":"Clear expectations make better work.","body":"These Terms of Use govern your access to this website and your interactions with Triad Studio. By using the website, submitting an enquiry or engaging us for a project, you agree to these terms. A signed proposal, quotation, order confirmation or project agreement may add to or replace these terms for that specific engagement."},"items":[],"design":{}},
          {"id":"terms_website","kind":"rich_text","label":"Using this website","visible":true,"mobileVisible":true,"content":{"heading":"Using this website","body":"You may use this website for lawful personal or business purposes. You must not misuse the website, interfere with its operation, introduce malicious code, attempt unauthorised access, scrape it in a way that harms our service, impersonate another person or use our content to infringe someone else's rights. We may suspend access where necessary to protect the website, our users or our business."},"items":[],"design":{}},
          {"id":"terms_information","kind":"rich_text","label":"Website information","visible":true,"mobileVisible":true,"content":{"heading":"Website information and availability","body":"We aim to keep the website accurate and current, but product details, colours, images, availability, prices and timelines may change without notice. Website content is provided for general information and is not a binding offer unless we expressly say otherwise. We do not promise that the website will always be available, error-free, secure or suitable for every purpose."},"items":[],"design":{}},
          {"id":"terms_enquiries","kind":"rich_text","label":"Enquiries and quotes","visible":true,"mobileVisible":true,"content":{"heading":"Enquiries, quotes and acceptance","body":"An enquiry is not an order or a binding commitment. A proposal or quotation will describe the relevant scope, assumptions, deliverables, price, taxes, payment schedule, revisions, production details and timing where applicable. Work begins when the required acceptance, deposit, purchase order or other agreed confirmation has been received. A quote may expire or need revision if its assumptions, materials, supplier costs or timing change."},"items":[],"design":{}},
          {"id":"terms_client","kind":"rich_text","label":"Client responsibilities","visible":true,"mobileVisible":true,"content":{"heading":"Your responsibilities","body":"You are responsible for providing accurate information, timely feedback, approvals, brand assets and content that you have the right to use. You must review proofs carefully and approve them before production or publication. Delays in receiving information, approvals or payment may change the delivery date and may result in additional costs that we will explain where reasonably possible."},"items":[],"design":{}},
          {"id":"terms_production","kind":"rich_text","label":"Design and production","visible":true,"mobileVisible":true,"content":{"heading":"Approvals, variations and production","body":"Design, print and manufactured items can have reasonable variations in colour, texture, scale, materials and finish. Screen previews may not exactly match physical output. Unless a project agreement says otherwise, extra concepts, revisions, copy changes, reprints caused by approved artwork, rush work, shipping changes or scope increases may be charged separately. We will seek approval for material changes to the agreed scope."},"items":[],"design":{}},
          {"id":"terms_payment","kind":"rich_text","label":"Payment and cancellation","visible":true,"mobileVisible":true,"content":{"heading":"Payment, cancellation and delivery","body":"Payment terms, deposits, taxes, delivery charges and cancellation rights are set out in the applicable quote or project agreement. Deposits may cover work already completed, committed materials or supplier costs and may not be refundable to that extent. Ownership or use rights may be withheld until amounts due are paid. Delivery dates are estimates unless expressly guaranteed, and delays caused by suppliers, couriers, events outside our reasonable control or late approvals may affect timing."},"items":[],"design":{}},
          {"id":"terms_ip","kind":"rich_text","label":"Intellectual property","visible":true,"mobileVisible":true,"content":{"heading":"Intellectual property","body":"Triad Studio retains rights in its pre-existing tools, methods, templates, processes, unused concepts and general know-how. You retain rights in materials you provide, and you give us permission to use them as needed to perform the project. Rights in final approved work transfer or are licensed only as stated in the applicable written agreement and, unless agreed otherwise, after outstanding invoices are settled. We may show completed work in our portfolio unless confidentiality terms say otherwise."},"items":[],"design":{}},
          {"id":"terms_third_party","kind":"rich_text","label":"Third-party materials","visible":true,"mobileVisible":true,"content":{"heading":"Third-party materials and links","body":"Projects may include fonts, stock assets, software, platforms, products or other materials supplied by third parties. Their licences, terms, availability and performance may apply separately, and you are responsible for complying with licences that are transferred to you. Links to third-party websites are provided for convenience; we do not control or endorse their content, security or practices."},"items":[],"design":{}},
          {"id":"terms_liability","kind":"rich_text","label":"Disclaimers and liability","visible":true,"mobileVisible":true,"content":{"heading":"Disclaimers and liability","body":"To the extent permitted by law, Triad Studio excludes implied warranties that cannot be excluded and is not responsible for indirect, incidental, special or consequential loss arising from use of the website or a project. Nothing in these terms excludes liability that cannot lawfully be excluded, including liability for fraud or applicable consumer rights. Any liability limits that apply to a particular engagement will be set out in the relevant project agreement."},"items":[],"design":{}},
          {"id":"terms_law","kind":"rich_text","label":"Governing law and contact","visible":true,"mobileVisible":true,"content":{"heading":"Governing law and contact","body":"These terms are governed by the laws of Kenya, unless a written project agreement states otherwise. We encourage you to contact us first so we can try to resolve a concern promptly. Questions about these terms can be sent to 3.triadstudio@gmail.com. We may update these terms by posting a revised version on this page, with the effective date shown above."},"items":[],"design":{}}
        ],
        "seo": {"title":"Terms of Use - Triad Studio","description":"Triad Studio terms of use.","canonical":"/terms"}
      }
      $$::jsonb
    ),
    (
      'cookies',
      $$
      {
        "version": 2,
        "pageId": "cookies",
        "title": "Cookie Policy",
        "description": "How Triad Studio uses cookies and similar technologies on this website.",
        "blocks": [
          {"id":"cookies_intro","kind":"rich_text","label":"Cookie Policy introduction","visible":true,"mobileVisible":true,"content":{"eyebrow":"Triad Studio | Effective 9 September 2026","heading":"A small note about cookies.","body":"This Cookie Policy explains how Triad Studio uses cookies, browser storage and similar technologies when you visit our website. It should be read together with our Privacy Policy, which explains how information connected with these technologies may be handled."},"items":[],"design":{}},
          {"id":"cookies_definition","kind":"rich_text","label":"What cookies are","visible":true,"mobileVisible":true,"content":{"heading":"What cookies are","body":"Cookies are small text files placed on your device by a website. Similar technologies can store or read information in your browser in other ways. These tools can help a website remember a session or preference, keep features working, understand broad usage patterns and improve reliability."},"items":[],"design":{}},
          {"id":"cookies_essential","kind":"rich_text","label":"Essential technologies","visible":true,"mobileVisible":true,"content":{"heading":"Essential cookies and storage","body":"Some cookies or browser storage are necessary for core functions such as security, session handling, remembering a technical preference or keeping a form and page working. Because the site may not function properly without them, these technologies may be used when you request the relevant service or where permitted by law."},"items":[],"design":{}},
          {"id":"cookies_functional","kind":"rich_text","label":"Functional technologies","visible":true,"mobileVisible":true,"content":{"heading":"Functional preferences","body":"Where enabled, preference technologies help us remember choices such as how the site behaves during your visit. These technologies are intended to make the experience more consistent, and they are not used to sell personal information."},"items":[],"design":{}},
          {"id":"cookies_analytics","kind":"rich_text","label":"Analytics technologies","visible":true,"mobileVisible":true,"content":{"heading":"Understanding site usage","body":"Where enabled, privacy-conscious analytics may help us understand which pages are useful, whether links work and how visitors move through the site. Analytics information is used to improve content and performance. We do not use this page to promise that a particular analytics provider is always active; the tools in use may change as the website changes."},"items":[],"design":{}},
          {"id":"cookies_third_party","kind":"rich_text","label":"Third-party content","visible":true,"mobileVisible":true,"content":{"heading":"Third-party content and links","body":"Embedded content, payment tools, maps, social features or links to other websites may be operated by third parties and may set their own cookies or similar technologies. Their practices are controlled by their own privacy and cookie policies. Review those policies before using a third-party feature or leaving our website."},"items":[],"design":{}},
          {"id":"cookies_controls","kind":"rich_text","label":"Cookie controls","visible":true,"mobileVisible":true,"content":{"heading":"Your controls","body":"You can block, delete or limit cookies through your browser settings. Your browser may also let you review stored site data and set rules for individual websites. Blocking essential storage can prevent parts of the site from working. If we introduce a consent control for optional technologies, you can use it to change your choice where available."},"items":[],"design":{}},
          {"id":"cookies_retention","kind":"rich_text","label":"Cookie duration and data","visible":true,"mobileVisible":true,"content":{"heading":"How long information is kept","body":"Some cookies last only until you close your browser, while others remain until they expire or you delete them. The duration depends on the purpose and the technology used. We keep information associated with cookies and analytics only as long as reasonably necessary for the relevant purpose, security, legal obligations or reporting."},"items":[],"design":{}},
          {"id":"cookies_changes","kind":"rich_text","label":"Changes and contact","visible":true,"mobileVisible":true,"content":{"heading":"Updates and questions","body":"We may update this policy when the website, providers or legal requirements change. The latest effective date will appear at the top of this page. Questions about our use of cookies can be sent to 3.triadstudio@gmail.com."},"items":[],"design":{}}
        ],
        "seo": {"title":"Cookie Policy - Triad Studio","description":"Triad Studio cookie policy.","canonical":"/cookies"}
      }
      $$::jsonb
    )
)
UPDATE public.page_content AS pages
SET draft = policy_documents.document,
    published = policy_documents.document,
    draft_revision = pages.draft_revision + 1,
    published_revision = pages.published_revision + 1,
    published_at = now(),
    updated_at = now()
FROM policy_documents
WHERE pages.page_id = policy_documents.page_id;

WITH policy_documents(page_id, document) AS (
  VALUES
    ('privacy', (SELECT published FROM public.page_content WHERE page_id = 'privacy')),
    ('terms', (SELECT published FROM public.page_content WHERE page_id = 'terms')),
    ('cookies', (SELECT published FROM public.page_content WHERE page_id = 'cookies'))
)
UPDATE public.page_published_content AS published_pages
SET document = policy_documents.document,
    revision = revision + 1,
    published_at = now()
FROM policy_documents
WHERE published_pages.page_id = policy_documents.page_id;